spring:
  application:
    name: ugly
  cloud:
    config:
      uri: http://192.168.99.100:8888


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
    healthcheck:
          enabled: true
  instance:
    prefer-ip-address: true


server:
  port: 8486

ugly:
   ribbon:
     # Eureka vipAddress of the target service

     # Interval to refresh the server list from the source (ms)
     ServerListRefreshInterval: 30000
     NIWSServerListClassName: com.zuul.MyServerList
     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # DeploymentContextBasedVipAddresses: ugly-service