server:
  port: 8761
security:
  user:
    password: ${eureka.password}
eureka:
  password: ${SECURITY_USER_PASSWORD:password}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
  client:
    preferSameZoneEureka: false
  instance:
    hostname: localhost
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:${eureka.password:${SECURITY_USER_PASSWORD:password}}@localhost:8761/eureka/