server:
  port: 8761
security:
  user:
    password: ${eureka.password}
eureka:
  password: ${SECURITY_USER_PASSWORD:password}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
  client:
    preferSameZoneEureka: false
  instance:
    hostname: 192.168.99.100
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
    prefer-ip-address: true
