spring:
  application:
    name: beatifull

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

beatifull:
   ribbon:
     # Eureka vipAddress of the target service
     NIWSServerListClassName: com.client.MyServerList
     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
     #DeploymentContextBasedVipAddresses: beatifull-service
     # Interval to refresh the server list from the source (ms)
     ServerListRefreshInterval: 30000
